"""add app module and app_status columns

Revision ID: add_app_module_status
Revises: 03ea244985ce
Create Date: 2025-12-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_app_module_status'
down_revision = '03ea244985ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('app_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('app_status')
        batch_op.drop_column('module')
    # ### end Alembic commands ###
